# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - detgrey-jokes-service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push container image to registry
      run: |
        docker build -t joke-service .
        docker tag joke-service:latest ${{ secrets.DOCKER_USERNAME }}/joke-service:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/joke-service:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'detgrey-jokes-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9dd38fb00de94f8e84c8496ecc7421a7 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_84ab9f2b90a54b09b96973b0cb2e90d7 }}/detgrey/jokes-service:${{ github.sha }}'
