# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - detgrey-jokes-service

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_2ef4622b77294f3b8727f34006634f5a }}
        password: ${{ secrets.AzureAppService_ContainerPassword_36e63a56f7de46908d60b6fed98d15a3 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2ef4622b77294f3b8727f34006634f5a }}/detgrey/jokes-service:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'detgrey-jokes-service'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_4cb2526f89e64e67a5420fc179866016 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_2ef4622b77294f3b8727f34006634f5a }}/detgrey/jokes-service:${{ github.sha }}'